language: php
sudo: false
services: mysql

env:
  global:
    - MIN_PHP=7.4
    - DATABASE_URL=mysql://travis@127.0.0.1:3306/adpay_test

matrix:
  include:
    - php: "7.4"
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:migrations:migrate -n --env=test

script:
  - composer qa-check
  - composer test-ci
  - git fetch --unshallow
  - sonar-scanner

addons:
  sonarcloud:
    organization: "adshares-github"
    token:
      secure: "LGt/hA4zB/M+3074MlKXDYZdg2u74IKGRURRqTbRuH6baFVvSr3ixCv/H5DvEBNQNGHUvkVJLuVILncBSsc6vyqI9HWUHObTCJPB8qEw35qjbRAfKfysyZ1hV6Ebx5p3ASzfStKp6nZjWy/A4KCr4nh9lceKOm2ERgjNC7GMkYpUx9BVLQSBILwAe+a4SQyYNo42IKO3JfbWuYx9pVyCksK2NEv5K1PBdq0YbJ2ZZthgdCd1+9Dt3Y7fNIvtVSkYTATRGUirTBwIXU/vIVPzTqoq4aeJhumhJ5PJ/eUuD3f/fgFshWkf0kw2mT09HYuZI59a5VcwzVImVKygXPt+6th1cWSXgfvpxc9bI/Yhljerk7LAMO1UWGB3D1fOsW7bbtgI40fdH5YmOFFdWnNzDdb+z6trU/xmmNiR8YwFBgCwmW/OK4vDctIRI3wwIYrnwXkb1ahUF4gJHYgL7PR3vSl3lJXxBTYaWG0Z/Ughi5Rrzws3OagXvs1y/9QewfcZlvJVfDsG3kPt6HDZjPKEaYXZu9TuYBAQQFL534+ULkAtSoYW7N3O4fZbEdvgcEUvZSchkcO4eq3w8y2siXB08C9DlwYapFCEwxhkmLyp9QDnvlILlG2mEzg23UMxSyWFh7IjHpJ2NN+PjkWqKPKVBAKAbd/Q+Zw43sTm675F7m4="
