import os

#: Seconds per hour (3600)
SECONDS_PER_HOUR = int(os.getenv('ADPAY_SECONDS_PER_HOUR', 3600))

#: Max keywords in a user profile
MAX_USER_KEYWORDS_IN_PROFILE = int(os.getenv('ADPAY_MAX_USER_KEYWORDS_IN_PROFILE', 50))

CALCULATION_METHOD = os.getenv('ADPAY_CALCULATION_METHOD', 'default')

CALCULATE_PAYMENTS_PERIODICALLY = bool(os.getenv('ADPAY_CALCULATE_TASKS', True))

VALIDATE_EVENT_KEYWORD_EQUALITY = bool(os.getenv('ADPAY_VALIDATE_EVENT_KEYWORD_EQUALITY', True))
VALIDATE_CAMPAIGN_FILTERS = bool(os.getenv('ADPAY_VALIDATE_CAMPAIGN_FILTERS', True))
