parameters:
    env(LOG_FILE_PATH): "%kernel.logs_dir%/%kernel.environment%.log"

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
        nested:
            type: stream
            path: '%env(LOG_FILE_PATH)%'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: '%env(LOG_FILE_PATH)%'
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
