# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    api_version: 'v1'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

#    Adshares\AdPay\UI\Command\:
#        resource: '../src/UI/Command'

#    Adshares\AdSelect\UI\EventListener\ApiExceptionListenerSubscriber:
#        arguments:
#            $env: '%env(APP_ENV)%'
#            $logger: '@logger'
#        tags:
#            - { name: kernel.event_subscriber }

#    Adshares\AdPay\Infrastructure\Doctrine\Client:
#        resource: '../src/Infrastructure/Doctrine/Client.php'

    Adshares\AdPay\Infrastructure\Doctrine\Service\:
        resource: '../src/Infrastructure/Doctrine/Service'

    Adshares\AdPay\UI\Controller\:
        resource: '../src/UI/Controller'
        tags: ['controller.service_arguments']

    Adshares\AdPay\UI\Controller\CampaignController:
        public: true
        arguments:
            $campaignUpdater: '@Adshares\AdPay\Infrastructure\Doctrine\Service\DoctrineCampaignUpdater'
            $logger: '@logger'